
image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: yarn install # runs during prebuild
    command: yarn start

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3333
  - port: 4200
    onOpen: open-preview
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - ms-azuretools.vscode-docker
    - nrwl.angular-console
    - esbenp.prettier-vscode
    - stylelint.vscode-stylelint
    
